eureka:
  client:
    service-url:
      defaultZone: http://peer2:7002/eureka/,http://peer1:7001/eureka/

---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 7001
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1

---
spring:
  profiles: peer2
server:
  port: 7002
eureka:
  instance:
    hostname: peer2